### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by mveytsman** [mveytsman/nixfiles#1]
- [ ] Put CPU temp in my i3 bar
- [ ] Move my user packages into a local nixpkgs config
- [ ] Make sure vscode and all my chatapps start at startup
- [ ] Filepicker doesn't work via flatpak
- [ ] https://github.com/mveytsman/dotfiles/issues/2
- [ ] https://github.com/mveytsman/dotfiles/issues/1
- [ ] set up home manager, move over packages directly configured in desktop.nix and in my nix-env.
- [ ] merge this repo with https://github.com/mveytsman/dotfiles
